name: Build Yamashina

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Install Windows App SDK
      run: |
        dotnet workload install microsoft-net-sdk-windowsdesktop
        dotnet workload install maui-windows

    - name: Restore NuGet packages
      run: nuget restore Yamashina.slnx

    - name: Restore dependencies
      run: dotnet restore Yamashina.slnx

    - name: Build
      run: msbuild Yamashina.slnx /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always /p:UapAppxPackageBuildMode=SideloadOnly /p:PublishReadyToRun=false /p:AppxPackageSigningEnabled=false /p:GenerateAppInstallerFile=true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: yamashina-winui3-build
        path: |
          **/bin/x64/Release/
          !**/bin/**/ref/
          !**/bin/**/refs/

    - name: Upload MSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: Yamashina-MSIX
        path: |
          **/*.msix
          **/*.msixbundle

